### PR TITLE
desktop.media.twitch_vod_fetch: Add Windows Support

### PR DESCRIPTION
**Pull request by Choonster**
This adds Windows support to the `twitch_vod_fetch` script.

### CODE REVIEW

**Comment by mk-fg** [comment]
Umm.... thanks, I think it'd be really cool if there'd be such thing for windows, but I don't want to maintain it ;(
And I suspect I'll be breaking it on changes anyway, as I won't be testing them on that platform.

If you're using it, even very occasionally, maybe you can fork the script into your own repository, and have proper windows version there?

...which I just realized you've done already with Choonster/fgtk, though it might be easier to have a separate repo/project for the thing, as you probably don't need all the other crap there.

I also just realized that some people might be reluctant to do that due to stupid licenses and such, so added a blurb about everything being WTFPL to the README file.

And I guess I'll add a link to your script version to the README and for when script detects Windows, so other people would be able to find it easily.
If you'll split it into separate project or something like that, would be great if you'd ping me or throw a PR to update that link.

Thanks!

**Comment by Choonster** [comment]
That's fair enough. I made the changes for my own needs, I thought I may as well share them with other people.

I can create a separate repo for the Windows-compatible version, but I probably won't actively maintain it or add new features beyond my own needs.

**Comment by mk-fg** [comment]
I think that'd still be way better than what would happen with these changes here ;)

Added a links to https://github.com/Choonster/fgtk#twitch-vod-fetch [to README](https://github.com/mk-fg/fgtk/#twitch_vod_fetch) and under `if sys.platform == 'win32':` btw.

**Comment by Choonster** [comment]
I've created a separate repository [here](https://github.com/Choonster/twitch_vod_fetch/).

**Comment by mk-fg** [comment]
Thanks. Updated all the links.

**Pull request closed without merging**
